destination: ./public
markdown: rdiscount
permalink: "/:title/"
exclude: Gemfile, Gemfile.lock, config.ru, README.markdown

paginate: 10

title: Unix and Me
subtitle: About unix, web programing and me
author: Dmitry Nix

category_dir: 'categories'

url: http://blog.dmitrynix.com
